### ISSUE TITLE
Current and/or future features

### ISSUE THREAD

**Issue by jnrosenb** [codefluegel/vuforia4unreal#10]
Hello there!

I would like to know whether this project has the capabilities to do Object tracking, or if right now it supports only Marker tracking.

If the later case, can it track any kind of marker? (like custom images via training), or only some standard ones? Also, is there work in progress to release object tracking in some future?

Thanks for your time!

Jose Rosenbluth

**Comment by geovie** [comment]
Hello,
right now the plugin only supports Image Target tracking, where the target can be any image defined in the vuforia target manager. See issue #2 for more.

It is planned to integrate Object tracking, but there is currently no one working on it and i don't know when it will happen. But as always any help would be appreciated!

**Comment by jnrosenb** [comment]
Thanks a lot for the quick reply!
