### ISSUE TITLE
UE4.17 support?

### ISSUE THREAD

**Issue by jBachalo** [codefluegel/vuforia4unreal#7]
Is there planned support for more recent version(s) of Unreal? Doesn't work for 4.17

Also 4.16.2 is no longer available as a version..with 4.16.3 I get an error message "Missing Vuforia TestModules..." and asking me to recompile the plugins..but it doesn't work  http://imgur.com/a/GL8o3

**Comment by geovie** [comment]
I have not tested it yet with 4.17, but there should not be much to change... What kind of errors are you getting?
I use 4.16.3 and it works, you have to recompile the plugins, if it doesn't work check the logs in _Saved/Logs/VuforiaTest.log_

**Comment by jBachalo** [comment]
ok thanks. Yes the plugins need recompiling.  Novice question, can I use VisualStudio2015 for this?

**Comment by geovie** [comment]
Yes you can use Visual Studio 2015!

**Comment by jBachalo** [comment]
Thanks for sharing this with the commmunity!
