### ISSUE TITLE
Missing Vuforia Test Modules

### ISSUE THREAD

**Issue by jBachalo** [codefluegel/vuforia4unreal#8]
Followed install directions exactly. Vuforia SDK is copied to correct location.

But when I try and open the project I get a popup error 

> Missing Vuforia Test Modules
> The following modules are missing or built with a different engine version.
> UE4Editor-Vuforiatest.dll
> UE4Editor-CFVuforia.dll
> Would you like to rebuild them now?

I am using UE4 4.16.3

**Comment by elitap** [comment]
See #9 #7
