### ISSUE TITLE
Compiling plugins

### ISSUE THREAD

**Issue by jBachalo** [codefluegel/vuforia4unreal#9]
Hi
Isn't the necessity of compiling the plugins first missing from the Build Instructions?
Any chance you could provide a walkthru for C++ novices using VisualStudio?

**Comment by geovie** [comment]
Yes, there should be at least a link to Visual Studio or something... I will add that!
After you have visual studio installed, Unreal will  automatically compile the plugin the first time you open the project. There is no interaction with Visual Studio needed to use the plugin!

**Comment by jBachalo** [comment]
Thanks! Wasn't aware of that. Thought compilation had to happen first in VS.
